name: generate plantuml
on: pull_request_target
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 1
    - name: install cargo
      run: curl -sSf https://static.rust-lang.org/rustup.sh | sh
    - name: check cargo
      run: echo cargo --version
    - name: install plantaznik
      run: cargo install plantaznik
    - name: generate uml
      run: plantaznik README.md
