name: generate plantuml
on: pull_request_target
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: C4Builder
        uses: clippings/c4builder-action@v1
